catalog:
  '@eslint/eslintrc': ^3.3.3
  '@iconify-json/mingcute': ^1.2.5
  '@intlify/unplugin-vue-i18n': ^11.0.1
  '@unhead/vue': ^2.0.19
  '@vitejs/plugin-vue': ^6.0.2
  '@vueuse/core': ^14.1.0
  eslint: ^9.39.1
  nprogress: ^0.2.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  unocss: ^66.5.10
  unplugin-auto-import: ^20.3.0
  unplugin-icons: ^22.5.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-router: ^0.19.0
  vite: ^7.2.6
  vite-plugin-inspect: ^11.3.3
  vite-plugin-vue-devtools: ^8.0.5
  vite-plugin-vue-layouts: ^0.11.0
  vue: ^3.5.25
  vue-i18n: ^11.2.2
  vue-macros: ^3.1.1
  vue-router: ^4.6.3

onlyBuiltDependencies:
  - esbuild
