/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IMingcute:home1Line': typeof import('~icons/mingcute/home1-line')['default']
    'IMingcute:user1Line': typeof import('~icons/mingcute/user1-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WrapHeader: typeof import('./components/WrapHeader.vue')['default']
  }
}
