/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'HomePage': RouteRecordInfo<
      'HomePage',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'NotFoundPage': RouteRecordInfo<
      'NotFoundPage',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    'UserPage': RouteRecordInfo<
      'UserPage',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'UserDetailPage': RouteRecordInfo<
      'UserDetailPage',
      '/user/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'HomePage'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | 'NotFoundPage'
      views:
        | never
    }
    'src/pages/user/index.vue': {
      routes:
        | 'UserPage'
      views:
        | never
    }
    'src/pages/user/[name].vue': {
      routes:
        | 'UserDetailPage'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
